### PR TITLE
Issue #268 Updated Apache config for not to encode %2F double

### PR DESCRIPTION
**Pull request by vasiliy-t**
Fix for issue [#268](https://github.com/gitlabhq/gitlab-recipes/issues/268)

### CODE REVIEW

**Comment by axilleas** [comment]
Thanks for the investigation and your time to provide a patch :)

Can you maybe apply it to all apache configs?

**Comment by vasiliy-t** [comment]
@axilleas Ok, it will take some time to test all available configurations.

**Comment by vasiliy-t** [comment]
@axilleas Done, tested all configs before commit. Should I squash commits?

**Comment by axilleas** [comment]
You rock! Yes, please rebase if possible.

**Comment by vasiliy-t** [comment]
@axilleas Done.

**Comment by axilleas** [comment]
:beers:

**Pull request merged**
