### PR TITLE
Update FreeBSD docs

### PR DESCRIPTION
**Pull request by charlesdunbar**
This adds updated docs for installing the latest GitLab on FreeBSD 10.3.

### CODE REVIEW

**Comment by rascal-hats** [comment]
Great update, thanks for the time you put into this.

I'd request a few changes to step [13. Nginx.](https://github.com/charlesdunbar/gitlab-recipes/blob/28bcb4e9c2d51e973d8fd97b18d04780a123f24f/install/freebsd/freebsd-10.md#13-nginx)

The steps that worked for me are:

```
mkdir -p /usr/local/etc/nginx/conf.d
mkdir -p /usr/local/etc/nginx/ssl
mkdir -p /var/log/nginx
fetch -o /usr/local/etc/nginx/conf.d/gitlab.conf https://gitlab.com/gitlab-org/gitlab-ce/raw/master/lib/support/nginx/gitlab-ssl
```

and editing my `/usr/local/etc/nginx/nginx.conf` file to look like this:
```
load_module /usr/local/libexec/nginx/ngx_mail_module.so;
load_module /usr/local/libexec/nginx/ngx_stream_module.so;

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    include /usr/local/etc/nginx/conf.d/*;
}
```

I also had to make the following changes to the file `/usr/local/etc/nginx/conf.d/gitlab.conf`
* change any reference to `/etc/*` to `/usr/local/etc/*`
* change `proxy_pass http://gitlab-workhorse;` to `proxy_pass http://unix:/home/git/gitlab/tmp/sockets/gitlab-workhorse.socket:/;`

The following changes should be made to the .md file:
* replace `git.example.com` with `YOUR_SERVER_FQDN`
* It would also be nice for a quick example to create a self signed ssl cert.
```
cd /usr/local/etc/nginx/ssl
openssl genrsa -out gitlab.key
openssl req -new -batch -subj "/C=US/ST=gitlab/L=gitlab/O=gitlab/CN=gitlab" -key gitlab.key -out gitlab.csr
openssl x509 -req -days 3650 -in gitlab.csr -signkey gitlab.key -out gitlab.crt

```
* The `pw` utility has been updated, to add a user to a group please use the following: `pw groupmod git -m www`. You can double check this with `id www`, eg:
```
root@GitLab:/home/git/gitlab # id www
uid=80(www) gid=80(www) groups=80(www),1001(git)
```

**Comment by charlesdunbar** [comment]
Well that was a bit longer delay that I liked.  Updated per your suggestions.

Changing proxy_pass http://gitlab-workhorse; isn't needed, as there's an upstream directive that points to the location you mentioned:

```
upstream gitlab-workhorse {
  server unix:/home/git/gitlab/tmp/sockets/gitlab-workhorse.socket fail_timeout=0;
}
```

**Comment by axilleas** [comment]
Thank you!

**Comment by rascal-hats** [comment]
@charlesdunbar thank you for the info, I completely missed that.

 I've updated my original post accordingly.

**Pull request merged**
